name: Deploy DAGs and Requirements to S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1  # Specify your AWS region

    - name: Sync DAGs to S3
      run: |
        aws s3 sync ./dag s3://tredence-airflow-bucket/dags/
        # aws s3 sync ./dag/plugins s3://tredence-airflow-bucket/dags/plugins/
        aws s3 sync ./dag/scripts s3://tredence-airflow-bucket/dags/scripts/

    # Copy requirements.txt to the root of the S3 bucket
    - name: Sync requirements.txt to S3
      run: |
        aws s3 cp ./requirements.txt s3://tredence-airflow-bucket/requirements.txt
